version: '3'

services: 
  database:
    image: postgres
    container_name: postgres-db
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports: 
      - 5432:5432
    volumes:
      - postgres-db-data:/var/lib/postgresql/data:rw
      - ./sql:/docker-entrypoint-initdb.d/

volumes:
  postgres-db-data: